var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(e,p,g){e!=Array.prototype&&e!=Object.prototype&&(e[p]=g.value)};$jscomp.getGlobal=function(e){return"undefined"!=typeof window&&window===e?e:"undefined"!=typeof global&&null!=global?global:e};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.symbolCounter_=0;$jscomp.Symbol=function(e){return $jscomp.SYMBOL_PREFIX+(e||"")+$jscomp.symbolCounter_++};
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var e=$jscomp.global.Symbol.iterator;e||(e=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[e]&&$jscomp.defineProperty(Array.prototype,e,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(e){var p=0;return $jscomp.iteratorPrototype(function(){return p<e.length?{done:!1,value:e[p++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(e){$jscomp.initSymbolIterator();e={next:e};e[$jscomp.global.Symbol.iterator]=function(){return this};return e};$jscomp.iteratorFromArray=function(e,p){$jscomp.initSymbolIterator();e instanceof String&&(e+="");var g=0,q={next:function(){if(g<e.length){var t=g++;return{value:p(t,e[t]),done:!1}}q.next=function(){return{done:!0,value:void 0}};return q.next()}};q[Symbol.iterator]=function(){return q};return q};
$jscomp.polyfill=function(e,p,g,q){if(p){g=$jscomp.global;e=e.split(".");for(q=0;q<e.length-1;q++){var t=e[q];t in g||(g[t]={});g=g[t]}e=e[e.length-1];q=g[e];p=p(q);p!=q&&null!=p&&$jscomp.defineProperty(g,e,{configurable:!0,writable:!0,value:p})}};$jscomp.polyfill("Array.prototype.keys",function(e){return e?e:function(){return $jscomp.iteratorFromArray(this,function(e){return e})}},"es6","es3");
(function(e){function p(a,c){function b(){}b.prototype=a;a=new b;for(var d in c)a[d]=c[d];c.toString!==Object.prototype.toString&&(a.toString=c.toString);return a}var g=function(){return l.__string_rec(this,"")},q=function(a,c){this.r=new RegExp(a,c.split("u").join(""))};q.__name__=!0;q.prototype={__class__:q};var t=function(){};t.__name__=!0;t.remove=function(a,c){c=a.indexOf(c);if(-1==c)return!1;a.splice(c,1);return!0};t.iter=function(a){return{cur:0,arr:a,hasNext:function(){return this.cur<this.arr.length},
next:function(){return this.arr[this.cur++]}}};Math.__name__=!0;var H=function(){};H.__name__=!0;H.field=function(a,c){try{return a[c]}catch(b){return null}};var G=function(){};G.__name__=!0;G.string=function(a){return l.__string_rec(a,"")};var E=function(){};E.__name__=!0;E.replace=function(a,c,b){return a.split(c).join(b)};var r=function(){};r.__name__=!0;var w=function(){};w.__name__=!0;w.__super__=r;w.prototype=p(r.prototype,{__class__:w});var u=function(){};u.__name__=!0;r=function(){};r.__name__=
!0;r.__interfaces__=[u];r.__super__=w;r.prototype=p(w.prototype,{__class__:r});w=function(){};w.__name__=!0;w.__super__=r;w.prototype=p(r.prototype,{__class__:w});u=function(){};u.__name__=!0;u.__super__=w;u.prototype=p(w.prototype,{__class__:u});r=function(){};r.__name__=!0;r.__super__=u;r.prototype=p(u.prototype,{__class__:r});var k=function(){};k.__name__=!0;k.init=function(){if(!k.inited){var a=window.navigator.userAgent.toLowerCase();if(-1!=a.indexOf("opera")||-1!=window.navigator.userAgent.indexOf("OPR"))k.browser=
h.OPERA;else if(-1!=a.indexOf("edge"))k.browser=h.EDGE;else if(-1!=a.indexOf("chrome"))k.browser=h.CHROME;else if(-1!=a.indexOf("safari"))k.browser=h.SAFARI;else if(-1!=a.indexOf("firefox"))k.browser=h.FIREFOX;else if(-1!=a.indexOf("msie")||1==!!window.document.documentMode)k.browser=h.IE;-1!=a.indexOf("android")?k.os=m.ANDROID:-1!=a.indexOf("linux")?k.os=m.LINUX:-1!=a.indexOf("windows")?k.os=m.WINDOWS:-1!=a.indexOf("iphone")||-1!=a.indexOf("ipod")||-1!=a.indexOf("ipad")?k.os=m.IOS:-1!=a.indexOf("mac")&&
(k.os=m.MACOS);k.inited=!0}};k.get_browser=function(){k.init();return k.browser};k.get_os=function(){k.init();return k.os};k.traceInfo=function(){};var h={__ename__:!0,__constructs__:"FIREFOX SAFARI IE EDGE CHROME OPERA".split(" "),FIREFOX:["FIREFOX",0]};h.FIREFOX.toString=g;h.FIREFOX.__enum__=h;h.SAFARI=["SAFARI",1];h.SAFARI.toString=g;h.SAFARI.__enum__=h;h.IE=["IE",2];h.IE.toString=g;h.IE.__enum__=h;h.EDGE=["EDGE",3];h.EDGE.toString=g;h.EDGE.__enum__=h;h.CHROME=["CHROME",4];h.CHROME.toString=g;
h.CHROME.__enum__=h;h.OPERA=["OPERA",5];h.OPERA.toString=g;h.OPERA.__enum__=h;var m={__ename__:!0,__constructs__:["WINDOWS","MACOS","LINUX","IOS","ANDROID"],WINDOWS:["WINDOWS",0]};m.WINDOWS.toString=g;m.WINDOWS.__enum__=m;m.MACOS=["MACOS",1];m.MACOS.toString=g;m.MACOS.__enum__=m;m.LINUX=["LINUX",2];m.LINUX.toString=g;m.LINUX.__enum__=m;m.IOS=["IOS",3];m.IOS.toString=g;m.IOS.__enum__=m;m.ANDROID=["ANDROID",4];m.ANDROID.toString=g;m.ANDROID.__enum__=m;var l=function(){};l.__name__=!0;l.getClass=function(a){if(a instanceof
Array&&null==a.__enum__)return Array;var c=a.__class__;if(null!=c)return c;a=l.__nativeClassName(a);return null!=a?l.__resolveNativeClass(a):null};l.__string_rec=function(a,c){if(null==a)return"null";if(5<=c.length)return"<...>";var b=typeof a;"function"==b&&(a.__name__||a.__ename__)&&(b="object");switch(b){case "function":return"<function>";case "object":if(a instanceof Array){if(a.__enum__){if(2==a.length)return a[0];b=a[0]+"(";c+="\t";for(var d=2,f=a.length;d<f;){var e=d++;b=2!=e?b+(","+l.__string_rec(a[e],
c)):b+l.__string_rec(a[e],c)}return b+")"}b=a.length;d="[";c+="\t";for(f=0;f<b;)e=f++,d+=(0<e?",":"")+l.__string_rec(a[e],c);return d+"]"}try{d=a.toString}catch(R){return"???"}if(null!=d&&d!=Object.toString&&"function"==typeof d&&(b=a.toString(),"[object Object]"!=b))return b;b=null;d="{\n";c+="\t";f=null!=a.hasOwnProperty;for(b in a)f&&!a.hasOwnProperty(b)||"prototype"==b||"__class__"==b||"__super__"==b||"__interfaces__"==b||"__properties__"==b||(2!=d.length&&(d+=", \n"),d+=c+b+" : "+l.__string_rec(a[b],
c));c=c.substring(1);return d+("\n"+c+"}");case "string":return a;default:return String(a)}};l.__interfLoop=function(a,c){if(null==a)return!1;if(a==c)return!0;var b=a.__interfaces__;if(null!=b)for(var d=0,f=b.length;d<f;){var e=d++;e=b[e];if(e==c||l.__interfLoop(e,c))return!0}return l.__interfLoop(a.__super__,c)};l.__instanceof=function(a,c){if(null==c)return!1;switch(c){case Array:return a instanceof Array?null==a.__enum__:!1;case K:return"boolean"==typeof a;case N:return!0;case L:return"number"==
typeof a;case O:return"number"==typeof a?(a|0)===a:!1;case String:return"string"==typeof a;default:if(null!=a)if("function"==typeof c){if(a instanceof c||l.__interfLoop(l.getClass(a),c))return!0}else{if("object"==typeof c&&l.__isNativeObj(c)&&a instanceof c)return!0}else return!1;return c==P&&null!=a.__name__||c==Q&&null!=a.__ename__?!0:a.__enum__==c}};l.__nativeClassName=function(a){a=l.__toStr.call(a).slice(8,-1);return"Object"==a||"Function"==a||"Math"==a||"JSON"==a?null:a};l.__isNativeObj=function(a){return null!=
l.__nativeClassName(a)};l.__resolveNativeClass=function(a){return e[a]};var f=function(){};f.__name__=!0;f.getWrapper=function(){return{has:f.has,getText:f.getText,getList:f.getList,root:f.root,moduleVersion:f.moduleVersion,loaderVersion:f.loaderVersion}};f.has=function(a){var c=f.resources;return null!=A[a]?c.existsReserved(a):c.h.hasOwnProperty(a)};f.getText=function(a){var c=f.resources;return null!=A[a]?c.getReserved(a):c.h[a]};f.getList=function(){for(var a=[],c=f.resources.keys();c.hasNext();){var b=
c.next();a.push(b)}return a};f.loadAll=function(a,c){for(var b=0,d=0;d<a.length;){var e=a[d];++d;f.has(e.path)||(b+=1,f.load(e,function(){--b;0==b&&c()}))}0==b&&c()};f.load=function(a,c){var b=a.path,d=f.resources;if(null!=A[b]?d.existsReserved(b):d.h.hasOwnProperty(b))c();else if(b=a.path,d=f.callbacks,null!=A[b]?d.existsReserved(b):d.h.hasOwnProperty(b))a=a.path,b=f.callbacks,(null!=A[a]?b.getReserved(a):b.h[a]).push(c);else switch(b=a.path,d=f.callbacks,c=[c],null!=A[b]?d.setReserved(b,c):d.h[b]=
c,c=F.getExtension(a.path),c){case "mp3":f.loadSound(a,f.finish);break;case "json":case "svg":f.loadText(a,f.finish);break;case "ttf":f.loadFont(a,f.finish);break;default:throw new y("Unsupported asset format: "+c);}};f.finish=function(a){var c=f.callbacks;c=null!=A[a]?c.getReserved(a):c.h[a];for(var b=0;b<c.length;){var d=c[b];++b;d()}f.callbacks.remove(a)};f.getUrl=function(a){switch(a.type[1]){case 0:return a.path;case 1:return""+f.root+a.path;case 2:return""+f.root+a.path+"?version="+f.moduleVersion;
case 3:return""+f.root+a.path+"?version="+f.loaderVersion}};f.loadFont=function(a,c){var b=f.getUrl(a);z.load(b,function(b){var d=a.path,e=f.resources;null!=A[d]?e.setReserved(d,b):e.h[d]=b;c(a.path)})};f.loadSound=function(a,c){var b=f.getUrl(a);x.load(b,function(d){if(null!=d){var e=f.resources;null!=A[b]?e.setReserved(b,d):e.h[b]=d;c(a.path)}else window.console.error('Could not load sound from "'+b+'"')})};f.loadText=function(a,c){var b=f.getUrl(a);I.request(b,n.GET,null,null,function(d,e){if(null==
e){e=a.path;var g=f.resources;null!=A[e]?g.setReserved(e,d):g.h[e]=d;c(a.path)}else window.console.error('Could not load text from "'+b+'"')})};f.loadScript=function(a,c){var b=f.getUrl(a),d=window.document.createElement("script");d.id=a.path;d.setAttribute("src",b);d.setAttribute("type","text/javascript");d.onload=function(){c()};window.document.getElementsByTagName("head")[0].appendChild(d)};var z=function(){};z.__name__=!0;z.addFontFace=function(a){var c=F.getName(a),b=[];b.push("\t@font-face {");
k.get_browser()==h.EDGE&&b.push("\t\tfont-display:swap;");b.push('\t\tfont-family:"'+c+'";');b.push('\t\tsrc: url("'+E.replace(a,".ttf",".eot")+'");');b.push('\t\tsrc: url("'+E.replace(a,".ttf",".eot")+'?#iefix") format("embedded-opentype"),');b.push('\t\turl("'+a+'") format("truetype"),');b.push('\t\turl("'+E.replace(a,".ttf",".svg")+"#"+c+'") format("svg");');b.push('\t\turl("'+E.replace(a,".ttf",".woff")+'") format("woff"),');b.push("\t\tfont-weight: normal;");b.push("\t\tfont-style: normal;");
b.push("\t}");a=b.join("\n");c=window.document.getElementsByTagName("head")[0];b=window.document.createElement("style");b.setAttribute("type","text/css");b.styleSheet?b.styleSheet.cssText=a.toString():b.appendChild(window.document.createTextNode(a));c.appendChild(b)};z.loadFontWithCanvasWidthChecking=function(a,c){var b=window.document.createElement("canvas");b.width=32;b.height=32;var d=b.getContext("2d");d.font="48px "+a;var e=d.measureText("BESbswy@123456789").width,f=-1,g=0,h,k;f=window.setInterval(function(){g+=
1;h=d.measureText("BESbswy@123456789").width!=e;k=3E3<=50*g;if(h||k){window.clearInterval(f);b=null;if(k){var l=window.document.createElement("div");l.innerHTML='<p style="font-family: '+a+';">Unable to load '+a+", time is expired</p>";window.document.body.appendChild(l);window.console.warn('Could not load web font "'+a+'", time expired')}h&&(l=window.document.createElement("div"),l.innerHTML='<p style="font-family: '+a+';">ABCQWL abcqwl @0123456789 '+a+" loaded</p>",window.document.body.appendChild(l));
c(k?!1:!0)}},50)};z.loadFontWithWidthChecking=function(a,c){var b=window.document.createElement("span");b.style.fontFamily='"'+a+'", "AdobeBlank"';b.style.position="absolute";b.style.top="-100px";var d=window.document.createTextNode("BESbswy@123456789");b.appendChild(d);window.document.body.appendChild(b);var e=-1,f=4E3,g,h;e=window.setInterval(function(){f-=50;g=0<b.offsetWidth;h=0>f;if(g||h)window.clearInterval(e),b.parentNode.removeChild(b),b=null,h&&window.console.warn('Could not load web font "'+
a+'", time expired'),c(h?!1:!0)},50)};z.loadFontWithFontFace=function(a,c,b){var d=new XMLHttpRequest;d.addEventListener("readystatechange",function(a){2==d.readyState&&200==d.status||3==d.readyState||4!=d.readyState||(new FontFace(c,d.response)).load().then(function(a){window.document.fonts.add(a);b(!0)},function(a){window.console.warn('Could not load web font "'+c+'" promise error\n'+a);b(!1)})});d.open("get",a);d.responseType="arraybuffer";d.send()};z.load=function(a,c){var b=F.getName(a);if(k.get_browser()==
h.IE||k.get_browser()==h.EDGE)z.addFontFace(a),z.loadFontWithWidthChecking(b,c);else{var d=k.get_browser()==h.SAFARI,e=k.get_os()==m.WINDOWS;d&&e?(z.addFontFace(a),z.loadFontWithCanvasWidthChecking(b,c)):z.loadFontWithFontFace(a,b,c)}};var D=function(){};D.__name__=!0;D.main=function(){k.traceInfo();window.conceptispuzzles_loader=D.init};D.init=function(a){var c=a.family+a.type,b="conceptispuzzles_"+c,d=H.field(D.versions,c);c={path:""+c+".js",type:v.MODULE};f.root=a.root;f.loaderVersion=D.versions.loader;
f.moduleVersion=d;f.loadScript(c,function(){var c=null;c=window[b].pop();var d=c.getAssets();f.loadAll(d,function(){var b=f.getWrapper();c.init(b,a)})})};var v={__ename__:!0,__constructs__:["GLOBAL","LOCAL","MODULE","LOADER"],GLOBAL:["GLOBAL",0]};v.GLOBAL.toString=g;v.GLOBAL.__enum__=v;v.LOCAL=["LOCAL",1];v.LOCAL.toString=g;v.LOCAL.__enum__=v;v.MODULE=["MODULE",2];v.MODULE.toString=g;v.MODULE.__enum__=v;v.LOADER=["LOADER",3];v.LOADER.toString=g;v.LOADER.__enum__=v;var x=function(){};x.__name__=!0;
x.load=function(a,c){var b=-1,d=new Audio;x.audioArray.push(d);d.onerror=function(){window.console.warn('Could not load sound (onError) "'+d.src+'"');c(null);-1!=x.audioArray.indexOf(d)&&t.remove(x.audioArray,d);-1!=b&&(window.clearInterval(b),b=-1)};d.onabort=function(){window.console.warn('Could not load sound (onAbort) "'+d.src+'"');c(null);-1!=x.audioArray.indexOf(d)&&t.remove(x.audioArray,d);-1!=b&&(window.clearInterval(b),b=-1)};d.onstalled=function(){window.console.warn('Could not load sound (onStalled) "'+
d.src+'"');c(null);-1!=x.audioArray.indexOf(d)&&t.remove(x.audioArray,d);-1!=b&&(window.clearInterval(b),b=-1)};d.oncanplaythrough=function(){c(d);-1!=x.audioArray.indexOf(d)&&t.remove(x.audioArray,d);-1!=b&&(window.clearInterval(b),b=-1)};d.src=a;d.preload="auto";d.volume=0;d.load();a=d.play();if(null!=a)a["catch"](function(a){});if(k.get_browser()==h.SAFARI){var e=4E3,f,g;b=window.setInterval(function(){e-=50;f=4==d.readyState;g=0>e;if(f||g)-1!=b&&(window.clearInterval(b),b=-1),g&&(window.console.warn('Timer expirede. Could not load sound "'+
d.src+'"'),c(null)),f&&c(d),-1!=x.audioArray.indexOf(d)&&t.remove(x.audioArray,d)},50)}};var n={__ename__:!0,__constructs__:"DELETE GET HEAD OPTIONS POST PUT".split(" "),DELETE:["DELETE",0]};n.DELETE.toString=g;n.DELETE.__enum__=n;n.GET=["GET",1];n.GET.toString=g;n.GET.__enum__=n;n.HEAD=["HEAD",2];n.HEAD.toString=g;n.HEAD.__enum__=n;n.OPTIONS=["OPTIONS",3];n.OPTIONS.toString=g;n.OPTIONS.__enum__=n;n.POST=["POST",4];n.POST.toString=g;n.POST.__enum__=n;n.PUT=["PUT",5];n.PUT.toString=g;n.PUT.__enum__=
n;var I=function(){};I.__name__=!0;I.request=function(a,c,b,d,e){var f=new XMLHttpRequest;null!=e&&(f.onload=function(){4==f.readyState&&(200==f.status?e(f.responseText,null):e(null,"Error requesting url: "+a))},f.onerror=function(){e(null,"Error requesting url: "+a)});null==c&&(c=n.GET);f.open(G.string(c),a);f.timeout=d;f.send(b)};var F=function(){};F.__name__=!0;F.getExtension=function(a){return a.split("?").shift().split(".").pop()};F.getName=function(a){return a.split("/").pop().split(".").shift()};
g=function(){};g.__name__=!0;u=function(){this.h={}};u.__name__=!0;u.__interfaces__=[g];u.prototype={setReserved:function(a,c){null==this.rh&&(this.rh={});this.rh["$"+a]=c},getReserved:function(a){return null==this.rh?null:this.rh["$"+a]},existsReserved:function(a){return null==this.rh?!1:this.rh.hasOwnProperty("$"+a)},remove:function(a){if(null!=A[a]){a="$"+a;if(null==this.rh||!this.rh.hasOwnProperty(a))return!1;delete this.rh[a]}else{if(!this.h.hasOwnProperty(a))return!1;delete this.h[a]}return!0},
keys:function(){return t.iter(this.arrayKeys())},arrayKeys:function(){var a=[],c;for(c in this.h)this.h.hasOwnProperty(c)&&a.push(c);if(null!=this.rh)for(c in this.rh)36==c.charCodeAt(0)&&a.push(c.substr(1));return a},__class__:u};var y=function(a){Error.call(this);this.val=a;this.message=String(a);Error.captureStackTrace&&Error.captureStackTrace(this,y)};y.__name__=!0;y.wrap=function(a){return a instanceof Error?a:new y(a)};y.__super__=Error;y.prototype=p(Error.prototype,{__class__:y});var B=function(a){if(a instanceof
Array&&null==a.__enum__)this.a=a,this.byteLength=a.length;else{this.a=[];for(var c=0;c<a;){var b=c++;this.a[b]=0}this.byteLength=a}};B.__name__=!0;B.sliceImpl=function(a,c){a=new M(this,a,null==c?null:c-a);c=new J(a.byteLength);(new M(c)).set(a);return c};B.prototype={slice:function(a,c){return new B(this.a.slice(a,c))},__class__:B};var C=function(){};C.__name__=!0;C._new=function(a,c,b){if("number"==typeof a){b=[];for(c=0;c<a;){var d=c++;b[d]=0}b.byteLength=b.length;b.byteOffset=0;b.buffer=new B(b)}else if(l.__instanceof(a,
B))null==c&&(c=0),null==b&&(b=a.byteLength-c),b=0==c?a.a:a.a.slice(c,c+b),b.byteLength=b.length,b.byteOffset=c,b.buffer=a;else if(a instanceof Array&&null==a.__enum__)b=a.slice(),b.byteLength=b.length,b.byteOffset=0,b.buffer=new B(b);else throw new y("TODO "+G.string(a));b.subarray=C._subarray;b.set=C._set;return b};C._set=function(a,c){if(l.__instanceof(a.buffer,B)){if(a.byteLength+c>this.byteLength)throw new y("set() outside of range");for(var b=0,d=a.byteLength;b<d;){var e=b++;this[e+c]=a[e]}}else if(a instanceof
Array&&null==a.__enum__){if(a.length+c>this.byteLength)throw new y("set() outside of range");b=0;for(d=a.length;b<d;)e=b++,this[e+c]=a[e]}else throw new y("TODO");};C._subarray=function(a,c){c=C._new(this.slice(a,c));c.byteOffset=a;return c};String.prototype.__class__=String;String.__name__=!0;Array.__name__=!0;var O={__name__:["Int"]},N={__name__:["Dynamic"]},L=Number;L.__name__=["Float"];var K=Boolean;K.__ename__=["Bool"];var P={__name__:["Class"]},Q={},A={},J=e.ArrayBuffer||B;null==J.prototype.slice&&
(J.prototype.slice=B.sliceImpl);var M=e.Uint8Array||C._new;w.DEBUG=!1;w.MAX_DIRTY_ZONES=10;r.IS_DIGIT=new q("\\d","");r.drawCals=0;k.inited=!1;l.__toStr={}.toString;f.resources=new u;f.callbacks=new u;D.versions={skyviewer:"1.0.189",hitplayer:"1.0.194",nurviewer:"1.0.189",calviewer:"1.0.191",batviewer:"1.0.190",dapviewer:"1.0.189",sliplayer:"1.0.192",capplayer:"1.0.207",fapplayer:"1.0.204",kakviewer:"1.0.190",mapviewer:"1.0.190",lapplayer:"1.0.195",papviewer:"1.0.196",sudviewer:"1.0.192",skyplayer:"1.0.192",
sapviewer:"1.0.189",bapviewer:"1.0.385",nurplayer:"1.0.194",calplayer:"1.0.212",batplayer:"1.0.189",dapplayer:"1.0.195",hasviewer:"1.0.193",ttlviewer:"1.0.188",kakplayer:"1.0.196",mapplayer:"1.0.194",hitviewer:"1.0.190",papplayer:"1.0.268",sudplayer:"1.0.229",loader:"1.0.2988",sliviewer:"1.0.192",sapplayer:"1.0.220",capviewer:"1.0.190",bapplayer:"1.0.404",fapviewer:"1.0.189",hasplayer:"1.0.190",ttlplayer:"1.0.193",lapviewer:"1.0.190"};x.audioArray=[];C.BYTES_PER_ELEMENT=1;D.main()})("undefined"!=
typeof window?window:"undefined"!=typeof global?global:"undefined"!=typeof self?self:this);
